mysql:
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  schema: ${MYSQL_DATABASE}
  url: ${MYSQL_URL}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.generate_statistics]": false
      "[hibernate.show_sql]": false